### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by micya**
Fix clicky link

### CODE REVIEW

**Comment by TruaShamu** [comment]
I'd totally make a hilarious comment here, but I'd get in trouble 🤣

**Comment by micya** [comment]
> I'd totally make a hilarious comment here, but I'd get in trouble 🤣

No jello for you!

**Comment by TruaShamu** [comment]
no no no  feed me jello jello jello jello

**Comment by TruaShamu** [comment]
wait i thought the comments were public

**Comment by TruaShamu** [comment]
noooo my shame my awful shame *hides head under pile of mango jello boxies and wails like a makki*

TwT

**Comment by TruaShamu** [comment]
am i terrible

**Pull request merged**
